name: Periodic Health Check
on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  ping_server:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Health Check endpoint
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-uhpf.onrender.com/health
          follow-redirect: false
          max-attempts: 3
          retry-delay: 20s
